tbl = {
	[1550] = {
		unidentifiedDisplayName = "Unidentified Book",
		unidentifiedResourceName = "ºÏ",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Book",
		identifiedResourceName = "ºÏ",
		identifiedDescriptionName = {
			"A book that's been put together sturdily enough to be wielded as a weapon in an emergency situation.",
			"________________________",
			"^0000CCType:^000000 Book",
			"^0000CCMagic Attack:^000000 50",
			"^0000CCAttack:^000000 10",
			"^0000CCWeight:^000000 60",
			"^0000CCWeapon Level:^000000 2",
			"________________________",
			"^0000CCRequirement:^000000",
			"Base Level 14",
			"Priest, Sage and Star Gladiator"
		},
		slotCount = 3,
		ClassNum = 15,
		costume = false
	},
	[1564] = {
		unidentifiedDisplayName = "Unidentified Book",
		unidentifiedResourceName = "ºÏ",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Encyclopedia",
		identifiedResourceName = "´ë¹é°ú»çÀü",
		identifiedDescriptionName = {
			"An encyclopedia distributed by a Prontera publisher that is famous for using solid binding in their books.",
			"Those struck by this book will swear the binding is diamond hard.",
			"________________________",
			"INT +3, DEX +2",
			"MATK +90",
			"MATK +110",
			"Critical +20",
			"Critical bonus increases according to the wearer's LUK.",
			"________________________",
			"^0000CCType:^000000 Book",
			"^0000CCAttack:^000000 110",
			"^0000CCWeight:^000000 200",
			"^0000CCWeapon Level:^000000 3",
			"________________________",
			"^0000CCRequirement:^000000",
			"Base Level 70",
			"Priest, Sage and Star Gladiator"
		},
		slotCount = 2,
		ClassNum = 15,
		costume = false
	},
	[1572] = {
		unidentifiedDisplayName = "Unidentified Book",
		unidentifiedResourceName = "ºÏ",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Principles of Magic",
		identifiedResourceName = "¸¶¹ýÀÇÁ¤¼®",
		identifiedDescriptionName = {
			"This helps students study and build a strong foundation of using magic.",
			"If you're having trouble... - Author: Sage S.",
			"________________________",
			"INT +3",
			"ATK +10",
			"MATK +90",
			"________________________",
			"Increases SP Recovery Rate by 5%.",
			"________________________",
			"When equipped with ^990099Librarian Glove^000000 and ^990099Pocket Watch^000000:",
			"INT +5",
			"MaxHP +700",
			"Decreases After Attack Delay by 5%.",
			"________________________",
			"^0000CCType:^000000 Book",
			"^0000CCAttack:^000000 60",
			"^0000CCWeight:^000000 30",
			"^0000CCWeapon Level:^000000 3",
			"________________________",
			"^0000CCRequirement:^000000",
			"Base Level 60",
			"Priest, Sage and Star Gladiator"
		},
		slotCount = 2,
		ClassNum = 15,
		costume = false
	},
	[1573] = {
		unidentifiedDisplayName = "Unidentified Book",
		unidentifiedResourceName = "ºÏ",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Ancient Magic",
		identifiedResourceName = "°í´ëÀÇ¸¶¹ý",
		identifiedDescriptionName = {
			"A book with a Very impressive phrase,'There is no royal road to learning.' on its cover.",
			"Practice makes perfect. If you keep trying, you'll be an expert before you know it.",
			"________________________",
			"MATK +10",
			"MATK +120",
			"________________________",
			"When equipped with ^990099Mage Coat^000000:",
			"INT +4",
			"MDEF +8",
			"MaxSP +10%",
			"________________________",
			"^0000CCType:^000000 Book",
			"^0000CCAttack:^000000 30",
			"^0000CCWeight:^000000 70",
			"^0000CCWeapon Level:^000000 3",
			"________________________",
			"^0000CCRequirement:^000000",
			"Base Level 70",
			"Priest, Sage and Star Gladiator"
		},
		slotCount = 2,
		ClassNum = 15,
		costume = false
	},
	[1574] = {
